services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      PGHOST: 0.0.0.0
    ports:
      - "5432:5432"
    networks:
      - backend-network

  backend-api:
    build:
      context: .  # El contexto sigue siendo la raiz
      dockerfile: Dockerfile  # Ahora apunta al Dockerfile en la raiz
    container_name: backend-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - backend-network
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres-db;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword"
  test-backend:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["dotnet", "test", "/p:CollectCoverage=true", "/p:CoverletOutputFormat=lcov"]
    volumes:
      - .:/app
    working_dir: /app
networks:
  backend-network:
    driver: bridge
